#!/usr/bin/env python3
"""Bake the terminal pixel-art ultracost mark into src/logo-data.js.

Dev-only (not run at runtime — the runtime is zero-dep Node). The source is the user's
1:1 reference rendering assets/logo-pixel-ref.png (a glowing orb on a stem above four
nested low-poly faceted chevrons, violet -> magenta -> pink, with black inter-tier gaps on
a dark canvas). We auto-crop to the mark, LANCZOS-downsample to a terminal-sized grid (this
anti-aliases the edges + gradient and bakes the low-poly facets straight from the
reference), then classify: dark canvas + black gaps -> transparent (null), bright near-white
top blob -> orb (kind 1, animated glow), everything else -> tier (kind 0). Because the
facets/gradient are baked from the reference, the runtime renderer does NOT re-apply facet
shading.

Run:  python3 scripts/generate-logo.py
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "logo-pixel-ref.png")
OUT = os.path.join(ROOT, "src", "logo-data.js")

TARGET_H = 30          # baked pixel-rows → TARGET_H/2 terminal rows (15)
DARK = 38              # luminance ≤ DARK → transparent (canvas + black gaps)
BG, TRI, ORB, STEM = None, 0, 1, 2


def lum(c):
    return (c[0] + c[1] + c[2]) / 3.0


def sat(c):
    return max(c) - min(c)


def build():
    img = Image.open(SRC).convert("RGB")
    px = img.load()
    iw, ih = img.size

    # Auto-crop to the bright mark (exclude the dark canvas + faint outer glow).
    minx, miny, maxx, maxy = iw, ih, 0, 0
    for y in range(ih):
        for x in range(iw):
            if lum(px[x, y]) > 55:
                if x < minx: minx = x
                if y < miny: miny = y
                if x > maxx: maxx = x
                if y > maxy: maxy = y
    pad = 4
    minx = max(0, minx - pad); miny = max(0, miny - pad)
    maxx = min(iw, maxx + pad); maxy = min(ih, maxy + pad)
    crop = img.crop((minx, miny, maxx, maxy))
    cw, ch = crop.size

    H = TARGET_H
    W = max(1, round(H * cw / ch))               # preserve aspect (cell ≈ square on screen)
    small = crop.resize((W, H), Image.LANCZOS)    # smooth, anti-aliased downsample
    sp = small.load()

    out_px = [[BG for _ in range(W)] for _ in range(H)]
    out_kind = [[0 for _ in range(W)] for _ in range(H)]
    for y in range(H):
        for x in range(W):
            c = sp[x, y]
            if lum(c) <= DARK:
                continue                          # transparent: canvas + black gaps
            out_px[y][x] = (c[0], c[1], c[2])
            # Orb = the near-white, low-saturation bright blob in the top band.
            out_kind[y][x] = ORB if (y < H * 0.30 and lum(c) > 185 and sat(c) < 70) else TRI

    return out_px, out_kind, W, H


def emit(px, kind, W, H):
    rows = []
    for y in range(H):
        cells = []
        for x in range(W):
            c = px[y][x]
            cells.append("null" if c is BG else f"[{c[0]},{c[1]},{c[2]},{kind[y][x]}]")
        rows.append("  [" + ",".join(cells) + "]")
    body = ",\n".join(rows)
    js = (
        "// GENERATED by scripts/generate-logo.py from assets/logo-pixel-ref.png — do not edit by hand.\n"
        "// Each cell is null (transparent) or [r, g, b, kind] with kind 0=tier 1=orb 2=stem.\n"
        f"export const LOGO = {{\n  w: {W},\n  h: {H},\n  px: [\n{body}\n  ]\n}};\n"
    )
    with open(OUT, "w") as f:
        f.write(js)
    return js


if __name__ == "__main__":
    px, kind, W, H = build()
    emit(px, kind, W, H)
    import sys
    glyph = {0: "#", 1: "O", 2: "|"}
    for y in range(H):
        sys.stderr.write("".join(glyph.get(kind[y][x]) if px[y][x] is not BG else "." for x in range(W)) + "\n")
    sys.stderr.write(f"baked {W}x{H}\n")
    print("wrote " + OUT)
